# Practice question


## Q1. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
* Suppose the following inputs are given to the program: 3, 5
* Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


In [2]:
## Import Li
import numpy as np

In [3]:
l=[]
r=int(input("enter Number of Row :"))
c=int(input("enter the Number of Columns :"))
for i in range(r):
    for j in range(c):
        l.append(i*j)
x=np.array(l).reshape(r,c)
print(x)

enter Number of Row :5
enter the Number of Columns :7
[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6]
 [ 0  2  4  6  8 10 12]
 [ 0  3  6  9 12 15 18]
 [ 0  4  8 12 16 20 24]]


In [ ]:
## For shape (5, 5)

In [8]:
l=[]
r=int(input("enter number of raw "))
c=int(input("enter number of columns "))
for i in range(r):
    for j in range(c):
        l.append(i*j)
                
x=np.array(l).reshape(5,5)
print(x)

enter number of raw 5
enter number of columns 5
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]


## for multi list

In [13]:
row_num = int(input("Input number of rows: "))
col_num = int(input("Input number of columns: "))
multi_list = [[0 for col in range(col_num)] for row in range(row_num)]

for row in range(row_num):
    for col in range(col_num):
        multi_list[row][col]= row*col

print(multi_list)

Input number of rows: 6
Input number of columns: 7
[[0, 0, 0, 0, 0, 0, 0], [0, 1, 2, 3, 4, 5, 6], [0, 2, 4, 6, 8, 10, 12], [0, 3, 6, 9, 12, 15, 18], [0, 4, 8, 12, 16, 20, 24], [0, 5, 10, 15, 20, 25, 30]]
